# We do not need sudo, but want to use trusty.
sudo: false
dist: trusty

language: node_js

# Run tests against the latest version of node, and the latest LTS.
node_js:
  - 5
  - 4.2
  - 0.12
  - 0.10
